# Generated by Django 4.2.3 on 2023-07-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='Product',
            new_name='product',
        ),
    ]
